import type * as vscode from 'vscode';

export const MIMO_MODELS: vscode.LanguageModelChatInformation[] = [
  {
    id: 'mimo-v2-pro',
    name: 'MiMo-V2-Pro',
    family: 'mimo',
    version: 'v2-pro',
    tooltip: 'Xiaomi',
    detail: 'Xiaomi',
    maxInputTokens: 1048576,
    maxOutputTokens: 131072,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'mimo-v2-flash',
    name: 'MiMo-V2-Flash',
    family: 'mimo',
    version: 'v2-flash',
    tooltip: 'Xiaomi',
    detail: 'Xiaomi',
    maxInputTokens: 262144,
    maxOutputTokens: 131072,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'mimo-v2-omni',
    name: 'MiMo-V2-Omni',
    family: 'mimo',
    version: 'v2-omni',
    tooltip: 'Xiaomi',
    detail: 'Xiaomi',
    maxInputTokens: 262144,
    maxOutputTokens: 131072,
    capabilities: { imageInput: true, toolCalling: true },
  },
];

export const GLM_MODELS: vscode.LanguageModelChatInformation[] = [
  {
    id: 'glm-5.1',
    name: 'GLM-5.1',
    family: 'glm',
    version: '5.1',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 204800,
    maxOutputTokens: 131072,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'glm-5-turbo',
    name: 'GLM-5 Turbo',
    family: 'glm',
    version: '5-turbo',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 204800,
    maxOutputTokens: 131072,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'glm-5v-turbo',
    name: 'GLM-5V-Turbo',
    family: 'glm',
    version: '5v-turbo',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 204800,
    maxOutputTokens: 131072,
    capabilities: { imageInput: true, toolCalling: true },
  },
  {
    id: 'glm-5',
    name: 'GLM-5',
    family: 'glm',
    version: '5',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 204800,
    maxOutputTokens: 131072,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'glm-4.7',
    name: 'GLM-4.7',
    family: 'glm',
    version: '4.7',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 204800,
    maxOutputTokens: 131072,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'glm-4.7-flash',
    name: 'GLM-4.7 Flash',
    family: 'glm',
    version: '4.7-flash',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 204800,
    maxOutputTokens: 131072,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'glm-4.6',
    name: 'GLM-4.6',
    family: 'glm',
    version: '4.6',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 204800,
    maxOutputTokens: 131072,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'glm-4.5',
    name: 'GLM-4.5',
    family: 'glm',
    version: '4.5',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 131072,
    maxOutputTokens: 98304,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'glm-4.5-air',
    name: 'GLM-4.5 Air',
    family: 'glm',
    version: '4.5-air',
    tooltip: 'Z.AI',
    detail: 'Z.AI',
    maxInputTokens: 131072,
    maxOutputTokens: 98304,
    capabilities: { imageInput: false, toolCalling: true },
  },
];

export const NIM_MODELS: vscode.LanguageModelChatInformation[] = [
  {
    id: 'gemma-4-31b-it',
    name: 'Gemma 4 31B IT',
    family: 'nvidia-nim',
    version: 'gemma-4-31b-it',
    tooltip: 'NVIDIA NIM',
    detail: 'NVIDIA',
    maxInputTokens: 262144,
    maxOutputTokens: 8192,
    capabilities: { imageInput: true, toolCalling: true },
  },
  {
    id: 'minimax-m2.5',
    name: 'MiniMax M2.5',
    family: 'nvidia-nim',
    version: 'minimax-m2.5',
    tooltip: 'NVIDIA NIM',
    detail: 'NVIDIA',
    maxInputTokens: 204800,
    maxOutputTokens: 16384,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'step-3.5-flash',
    name: 'Step 3.5 Flash',
    family: 'nvidia-nim',
    version: 'step-3.5-flash',
    tooltip: 'NVIDIA NIM',
    detail: 'NVIDIA',
    maxInputTokens: 262144,
    maxOutputTokens: 16384,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'glm-4.7',
    name: 'GLM-4.7',
    family: 'nvidia-nim',
    version: 'glm-4.7',
    tooltip: 'NVIDIA NIM',
    detail: 'NVIDIA',
    maxInputTokens: 204800,
    maxOutputTokens: 16384,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'devstral-2-123b-instruct-2512',
    name: 'Devstral 2 123B Instruct',
    family: 'nvidia-nim',
    version: 'devstral-2-123b-instruct-2512',
    tooltip: 'NVIDIA NIM',
    detail: 'NVIDIA',
    maxInputTokens: 262144,
    maxOutputTokens: 16384,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'kimi-k2-instruct-0905',
    name: 'Kimi K2 Instruct 0905',
    family: 'nvidia-nim',
    version: 'kimi-k2-instruct-0905',
    tooltip: 'NVIDIA NIM',
    detail: 'NVIDIA',
    maxInputTokens: 262144,
    maxOutputTokens: 16384,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'qwen3-coder-480b-a35b-instruct',
    name: 'Qwen3 Coder 480B',
    family: 'nvidia-nim',
    version: 'qwen3-coder-480b-a35b-instruct',
    tooltip: 'NVIDIA NIM',
    detail: 'NVIDIA',
    maxInputTokens: 262144,
    maxOutputTokens: 16384,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'kimi-k2-instruct',
    name: 'Kimi K2 Instruct',
    family: 'nvidia-nim',
    version: 'kimi-k2-instruct',
    tooltip: 'NVIDIA NIM',
    detail: 'NVIDIA',
    maxInputTokens: 131072,
    maxOutputTokens: 16384,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'magistral-small-2506',
    name: 'Magistral Small 2506',
    family: 'nvidia-nim',
    version: 'magistral-small-2506',
    tooltip: 'NVIDIA NIM',
    detail: 'NVIDIA',
    maxInputTokens: 131072,
    maxOutputTokens: 16384,
    capabilities: { imageInput: false, toolCalling: false },
  },
  {
    id: 'granite-3.3-8b-instruct',
    name: 'Granite 3.3 8B Instruct',
    family: 'nvidia-nim',
    version: 'granite-3.3-8b-instruct',
    tooltip: 'NVIDIA NIM',
    detail: 'NVIDIA',
    maxInputTokens: 131072,
    maxOutputTokens: 8192,
    capabilities: { imageInput: false, toolCalling: true },
  },
  {
    id: 'qwq-32b',
    name: 'QwQ 32B',
    family: 'nvidia-nim',
    version: 'qwq-32b',
    tooltip: 'NVIDIA NIM',
    detail: 'NVIDIA',
    maxInputTokens: 131072,
    maxOutputTokens: 32768,
    capabilities: { imageInput: false, toolCalling: false },
  },
  {
    id: 'falcon3-7b-instruct',
    name: 'Falcon 3 7B Instruct',
    family: 'nvidia-nim',
    version: 'falcon3-7b-instruct',
    tooltip: 'NVIDIA NIM',
    detail: 'NVIDIA',
    maxInputTokens: 32768,
    maxOutputTokens: 8192,
    capabilities: { imageInput: false, toolCalling: false },
  },
];
